/**
 * Generate public/_redirects for Cloudflare Pages.
 *
 * Sources its state list from src/lib/geo/states.ts so the redirect block
 * stays in sync with the canonical state map. Run this whenever the map
 * changes; commit the result.
 *
 * Redirect priorities (top matches first in Cloudflare Pages):
 *   1. Host canonicalization (non-www → www)
 *   2. Legacy state-code aliases (/al/* → /alabama/*)
 *   3. Legacy state-code root pages (/al → /alabama)
 */

import { writeFileSync } from "fs";
import { resolve } from "path";
import { STATE_CODE_TO_NAME, STATE_NAME_TO_SLUG, type StateCode } from "../src/lib/geo/states";

const ROOT = resolve(__dirname, "..");
const OUT = resolve(ROOT, "public/_redirects");

const lines: string[] = [];

lines.push("# Auto-generated by scripts/generate-redirects.ts");
lines.push("# Do not edit by hand. Regenerate via: npx tsx scripts/generate-redirects.ts");
lines.push("");

lines.push("# --- Host canonicalization: non-www → www ---");
lines.push("https://peptidesnearby.com/*    https://www.peptidesnearby.com/:splat 301!");
lines.push("http://peptidesnearby.com/*     https://www.peptidesnearby.com/:splat 301!");
lines.push("http://www.peptidesnearby.com/* https://www.peptidesnearby.com/:splat 301!");
lines.push("");

lines.push("# --- Legacy state-code aliases: /al/* → /alabama/* (all 50 + DC + territories) ---");
const codes = Object.keys(STATE_CODE_TO_NAME) as StateCode[];
for (const code of codes) {
  const name = STATE_CODE_TO_NAME[code];
  const slug = STATE_NAME_TO_SLUG[name.toLowerCase()];
  if (!slug) continue;
  const lowerCode = code.toLowerCase();
  // Skip codes that equal the canonical slug (none currently, but future-proof)
  if (lowerCode === slug) continue;
  lines.push(`/${lowerCode}/*  /${slug}/:splat  301`);
}
lines.push("");

lines.push("# --- Legacy state-code root pages: /al → /alabama ---");
for (const code of codes) {
  const name = STATE_CODE_TO_NAME[code];
  const slug = STATE_NAME_TO_SLUG[name.toLowerCase()];
  if (!slug) continue;
  const lowerCode = code.toLowerCase();
  if (lowerCode === slug) continue;
  lines.push(`/${lowerCode}  /${slug}  301`);
}
lines.push("");

// Also catch the telehealth state-code variants
lines.push("# --- Legacy telehealth state-code aliases ---");
for (const code of codes) {
  const name = STATE_CODE_TO_NAME[code];
  const slug = STATE_NAME_TO_SLUG[name.toLowerCase()];
  if (!slug) continue;
  const lowerCode = code.toLowerCase();
  if (lowerCode === slug) continue;
  lines.push(`/telehealth/${lowerCode}  /telehealth/${slug}  301`);
}
lines.push("");

writeFileSync(OUT, lines.join("\n"));
console.log(`Wrote ${lines.length} lines to public/_redirects`);
